# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

In [22]:
import numpy as np
r = np.arange(1,11) 
print(r)

[ 1  2  3  4  5  6  7  8  9 10]


---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

In [20]:
a = np.zeros((3,3))  
print(a)  

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [24]:
a = np.zeros((3,3),dtype=int)  
print(a)  

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [26]:
r.dtype

dtype('int32')

---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

In [30]:
A = np.linspace(0,5,10)
print(A)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [32]:
A = np.linspace(0,5,10,endpoint=False)
print(A)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

In [36]:
A=np.eye((5), dtype=int)
print(A)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

In [40]:
A= np.random.rand(4,4)
print(A)

[[0.20445168 0.58365572 0.70694741 0.17440213]
 [0.0563876  0.12712635 0.25469875 0.14362482]
 [0.94864193 0.19769739 0.20120273 0.55891701]
 [0.57395133 0.99995747 0.49333003 0.50367553]]


In [46]:
A= np.random.random((4,4))
print(A)

[[0.54888802 0.907741   0.93362478 0.61612818]
 [0.66458629 0.33362814 0.2113342  0.42997993]
 [0.9674726  0.90997908 0.73817788 0.62826219]
 [0.31595835 0.22015634 0.19971592 0.19691108]]


In [66]:
np.random.seed(10)

In [68]:
A= np.random.rand(4,4)
print(A)

[[0.77132064 0.02075195 0.63364823 0.74880388]
 [0.49850701 0.22479665 0.19806286 0.76053071]
 [0.16911084 0.08833981 0.68535982 0.95339335]
 [0.00394827 0.51219226 0.81262096 0.61252607]]


In [72]:
A= np.random.rand(4,4)
print(A)

[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]]


In [70]:
np.random.seed(0)

---

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

In [86]:
A.shape

(4, 4)

---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

In [90]:
A.reshape((4,4))
print(A)

[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]]


---

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

In [92]:
A.dtype

dtype('float64')

---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

In [104]:
A=np.arange(1,101)
for i in A:
    if i %  2 == 0:
        print(i)
    else:
        print(" ")


 
2
 
4
 
6
 
8
 
10
 
12
 
14
 
16
 
18
 
20
 
22
 
24
 
26
 
28
 
30
 
32
 
34
 
36
 
38
 
40
 
42
 
44
 
46
 
48
 
50
 
52
 
54
 
56
 
58
 
60
 
62
 
64
 
66
 
68
 
70
 
72
 
74
 
76
 
78
 
80
 
82
 
84
 
86
 
88
 
90
 
92
 
94
 
96
 
98
 
100


In [106]:
A= np.arange(2,101,2)
print(A)


[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

In [120]:
A= np.random.rand(6,6)
print(A)

[[0.0202184  0.83261985 0.77815675 0.87001215 0.97861834 0.79915856]
 [0.46147936 0.78052918 0.11827443 0.63992102 0.14335329 0.94466892]
 [0.52184832 0.41466194 0.26455561 0.77423369 0.45615033 0.56843395]
 [0.0187898  0.6176355  0.61209572 0.616934   0.94374808 0.6818203 ]
 [0.3595079  0.43703195 0.6976312  0.06022547 0.66676672 0.67063787]
 [0.21038256 0.1289263  0.31542835 0.36371077 0.57019677 0.43860151]]


---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

---

In [218]:
A = np.array([[1,2], [3,4]])
print(A)
print(A.shape)

[[1 2]
 [3 4]]
(2, 2)


In [137]:
print(A[:1,1:2])

[[2]]


### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

---

In [139]:
np.sum(A)

10

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

---

In [159]:
A= np.arange(1,100)
print(A)
np.mean(A)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


50.0

In [161]:
np.median(A)

50.0

In [171]:
np.std(A)

28.577380332470412

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

---

In [177]:
np.max(A)

99

In [179]:
np.min(A)

1

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

---

In [203]:
X=np.random.rand(20)
print(X)
print('\t')
print(np.argmax(X))


[0.51820071 0.02566272 0.20747008 0.42468547 0.37416998 0.46357542
 0.27762871 0.58678435 0.86385561 0.11753186 0.51737911 0.13206811
 0.71685968 0.3960597  0.56542131 0.18327984 0.14484776 0.48805628
 0.35561274 0.94043195]
	
19


### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

---

In [207]:
N= np.arange(1,11)
print(N[::-1])

[10  9  8  7  6  5  4  3  2  1]


### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

---

In [220]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[3,2,1],[5,6,4],[6,2,3]])
C = np.multiply(A,B)
print(C)

[[ 3  4  3]
 [20 30 24]
 [42 16 27]]


### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

---

In [229]:
print(np.diag(C))

[ 3 30 27]


### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

---

In [235]:
A = np.array([[1,2],[2,3]])
B = np.array([[1,2],[2,3]])
C = np.multiply(A,B)
print(C)

[[1 4]
 [4 9]]


### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

---

In [21]:
import numpy as np
'''
Using numbers from 10 to 13
'''
y = np.arange(10, 14).reshape((2, 2))  
print(y)
'''
Flatten the matrix into a 1D array
'''
flattened_y = y.flatten()   
print(flattened_y)


[[10 11]
 [12 13]]
[10 11 12 13]


### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

---

In [29]:
#Stack two NumPy arrays vertically
import numpy as np
x=np.array([7, 8, 9])  
y=np.array([10, 11, 12]) 
result = np.vstack((x, y))  
print(result)

[[ 7  8  9]
 [10 11 12]]


### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

---

In [33]:
import numpy as np
x=np.array([7, 8, 9])  
y=np.array([13, 14, 15])  
result=np.hstack((x, y))  
print(result)

[ 7  8  9 13 14 15]


### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

---

In [43]:
import numpy as np
def stack_arrays(ar1, ar2):
    """
    Horizontally stacks two arrays into a single array.
    
    """
    return np.hstack((ar1, ar2))
x = np.array([11, 22, 33])
y = np.array([44, 55, 66])
msb = stack_arrays(x, y)
print(msb)


[11 22 33 44 55 66]


### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

---

In [45]:
import numpy as np
'''
 Generate a random array with new dimensions
'''
R = np.random.rand(2, 5)  
R_rounded = np.round(R, 3)  
print(R_rounded)

[[0.577 0.602 0.471 0.694 0.854]
 [0.656 0.51  0.623 0.443 0.464]]


### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

---

In [49]:
import numpy as np
s=np.array([8, 9, 10, 8, 6, 5, 9])
unique_elts = np.unique(s)  
print(unique_elts)


[ 5  6  8  9 10]


### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

---

In [53]:
import numpy as np
def replace_elts(arr, threshold):
    """
    Replaces all values in the array that are below the given threshold with the threshold value.
    """
    arr[arr < threshold] = threshold
    return arr
x=np.array([12, 7, 4, 20, 15, 2, 6, 11])
threshold_value = 8
r=replace_elts(x, threshold_value)
print(r)

[12  8  8 20 15  8  8 11]


### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

In [61]:
import numpy as np
c = np.array([7, 3, 0, 12, 0, 8, 6, 0, 2, 5, 4,3,9])  
non_zero_count = np.count_nonzero(c)  
print(non_zero_count)

10


### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

---

In [ ]:
### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

---

In [ ]:
### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57

```
---

In [ ]:





### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---